### ISSUE TITLE
Add and run brakeman (epic)

### ISSUE THREAD

**Issue by hortongn** [uclibs/aaec#145]
Documentation: https://github.com/presidentbeef/brakeman

Add the brakeman gem to the Gemfile, bundle install, and then run `bundle exec brakeman -q -w 2` to find any security vulnerabilities.  Create a new issue for each vulnerability found.

Verify previously found Brakeman vulnerabilities:
- [ ] https://github.com/uclibs/aaec/issues/147
- [ ] https://github.com/uclibs/aaec/issues/148
- [ ] https://github.com/uclibs/aaec/issues/149
- [ ] https://github.com/uclibs/aaec/issues/150

After all vulnerabilities have been found, run Brakeman automatically in CircleCI.  
Example: https://github.com/uclibs/treatment_database/blob/qa/.circleci/config.yml#L86-L89
- [ ] https://github.com/uclibs/aaec/issues/155

This can be multiple pull requests.
